version: '2.4'

services:
  bavenir-adapter:
    container_name: bavenir-adapter
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    volumes:
    - .:/app:delegated
    depends_on:
      cache-db:
        condition: service_healthy
  proxy:
    container_name: proxy
    volumes:
    - ./nginx/nginx_local.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      cache-db:
        condition: service_healthy
    ports:
    - 9997:9997
    image: nginx:1.15-alpine
  gateway:
    container_name: gateway
    # restart: always
    volumes:
    # - ./gateway/log:/gateway/log
    - ./gateway/GatewayConfig.xml:/gateway/config/GatewayConfig.xml:ro
    - ./gateway/keystore:/gateway/keystore
    environment:
    - UID=9999
    - GID=9999
    ports:
    - 8181:8181
    # image: gtw-api:latest
    image: bavenir/vicinity-gateway-api:latest
  cache-db:
    container_name: cache-db
    restart: always
    # ports:
    # - 6379:6379
    volumes:
    - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    command:
    - /usr/local/etc/redis/redis.conf
    image: redis:buster